@baseUrl = http://localhost:3333
@token = {{autenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "123456"
}

###

# @name autenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "123456"
}

###

# @name create_cars
POST {{baseUrl}}/cars
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "mark": "Ford",
    "model": "Mustang",
    "year": 1969,
    "color": "Vermelho",
    "price": 100000
}